[package]
name = "bsv-wasm"
version = "2.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2.87" }
bsv = { path = "../.." }
serde-wasm-bindgen = "0.6.0"
console_error_panic_hook = { version = "0.1.7", optional = true }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[dependencies.getrandom]
version = "0.2.10"
features = ["js"]
